[
  {":0:unknown_function Function :erl_types.t_is_opaque/1/1 does not exist."},
  {":0:unknown_function Function :erl_types.t_to_string/1 does not exist."},
  {"lib/dialyxir/pretty_print.ex", :no_return, 100},
  {"lib/dialyxir/pretty_print.ex", :no_return, 121},
  {"lib/dialyxir/pretty_print.ex", :no_return, 69},
  {"lib/dialyxir/pretty_print.ex", :no_return, 81},
  {"lib/dialyxir/warning_helpers.ex", :no_return, 8},
  {"lib/dialyxir/warnings/app_call.ex", :no_return, 17},
  {"lib/dialyxir/warnings/apply.ex", :no_return, 16},
  {"lib/dialyxir/warnings/binary_construction.ex", :no_return, 16},
  {"lib/dialyxir/warnings/call.ex", :no_return, 16},
  {"lib/dialyxir/warnings/callback_argument_type_mismatch.ex", :no_return, 20},
  {"lib/dialyxir/warnings/callback_spec_argument_type_mismatch.ex", :no_return, 20},
  {"lib/dialyxir/warnings/callback_spec_type_mismatch.ex", :no_return, 19},
  {"lib/dialyxir/warnings/callback_type_mismatch.ex", :no_return, 17},
  {"lib/dialyxir/warnings/contract_diff.ex", :no_return, 16},
  {"lib/dialyxir/warnings/contract_subtype.ex", :no_return, 16},
  {"lib/dialyxir/warnings/contract_supertype.ex", :no_return, 16},
  {"lib/dialyxir/warnings/contract_with_opaque.ex", :no_return, 16},
  {"lib/dialyxir/warnings/exact_equality.ex", :no_return, 16},
  {"lib/dialyxir/warnings/extra_range.ex", :no_return, 19},
  {"lib/dialyxir/warnings/function_application_arguments.ex", :no_return, 16},
  {"lib/dialyxir/warnings/function_application_no_function.ex", :no_return, 16},
  {"lib/dialyxir/warnings/guard_fail_pattern.ex", :no_return, 16},
  {"lib/dialyxir/warnings/improper_list_construction.ex", :no_return, 16},
  {"lib/dialyxir/warnings/invalid_contract.ex", :no_return, 17},
  {"lib/dialyxir/warnings/pattern_match.ex", :no_return, 16},
  {"lib/dialyxir/warnings/pattern_match_covered.ex", :no_return, 16},
  {"lib/dialyxir/warnings/race_condition.ex", :no_return, 10},
  {"lib/dialyxir/warnings/race_condition.ex", :no_return, 14},
  {"lib/dialyxir/warnings/unmatched_return.ex", :no_return, 16}
]
