[
  {"/home/travis/otp/19.2/lib/parsetools-2.1.4/include/leexinc.hrl", :unused_fun, 276},
  {":0:unknown_function Function :erl_types.t_is_opaque/1 does not exist."},
  {":0:unknown_function Function :erl_types.t_to_string/1 does not exist."},
  {":0:unknown_type Unknown type: :cerl.c_fun/0."},
  {":0:unknown_type Unknown type: :cerl.cerl/0."},
  {":0:unknown_type Unknown type: :erl_types.erl_type/0."},
  {":0:unknown_type Unknown type: :erl_types.type_table/0."},
  {":0:unknown_type Unknown type: :wx.wx_colour/0."},
  {":0:unknown_type Unknown type: :wx.wx_datetime/0."},
  {":0:unknown_type Unknown type: :wx.wx_enum/0."},
  {":0:unknown_type Unknown type: :wx.wx_object/0."},
  {":0:unknown_type Unknown type: :wx.wx_wxHtmlLinkInfo/0."},
  {":0:unknown_type Unknown type: :wxAuiManager.wxAuiManager/0."},
  {":0:unknown_type Unknown type: :wxAuiNotebook.wxAuiNotebook/0."},
  {":0:unknown_type Unknown type: :wxAuiPaneInfo.wxAuiPaneInfo/0."},
  {":0:unknown_type Unknown type: :wxCursor.wxCursor/0."},
  {":0:unknown_type Unknown type: :wxDC.wxDC/0."},
  {":0:unknown_type Unknown type: :wxFont.wxFont/0."},
  {":0:unknown_type Unknown type: :wxMenu.wxMenu/0."},
  {":0:unknown_type Unknown type: :wxWindow.wxWindow/0."},
  {"lib/dialyxir/pretty_print.ex", :no_return},
  {"lib/dialyxir/warning_helpers.ex", :no_return},
  {"lib/dialyxir/warnings/app_call.ex", :no_return},
  {"lib/dialyxir/warnings/apply.ex", :no_return},
  {"lib/dialyxir/warnings/binary_construction.ex", :no_return},
  {"lib/dialyxir/warnings/call.ex", :no_return},
  {"lib/dialyxir/warnings/callback_argument_type_mismatch.ex", :no_return},
  {"lib/dialyxir/warnings/callback_spec_argument_type_mismatch.ex", :no_return},
  {"lib/dialyxir/warnings/callback_spec_type_mismatch.ex", :no_return},
  {"lib/dialyxir/warnings/callback_type_mismatch.ex", :no_return},
  {"lib/dialyxir/warnings/contract_diff.ex", :no_return},
  {"lib/dialyxir/warnings/contract_subtype.ex", :no_return},
  {"lib/dialyxir/warnings/contract_supertype.ex", :no_return},
  {"lib/dialyxir/warnings/contract_with_opaque.ex", :no_return},
  {"lib/dialyxir/warnings/exact_equality.ex", :no_return},
  {"lib/dialyxir/warnings/extra_range.ex", :no_return},
  {"lib/dialyxir/warnings/function_application_arguments.ex", :no_return},
  {"lib/dialyxir/warnings/function_application_no_function.ex", :no_return},
  {"lib/dialyxir/warnings/guard_fail_pattern.ex", :no_return},
  {"lib/dialyxir/warnings/improper_list_construction.ex", :no_return},
  {"lib/dialyxir/warnings/invalid_contract.ex", :no_return},
  {"lib/dialyxir/warnings/pattern_match.ex", :no_return},
  {"lib/dialyxir/warnings/pattern_match_covered.ex", :no_return},
  {"lib/dialyxir/warnings/race_condition.ex", :no_return},
  {"lib/dialyxir/warnings/unmatched_return.ex", :no_return}
]
